#!/usr/bin/env bash

# Run the script that goes to infinity
./4-to_infinity_and_beyond &

# Save the PID of the last background process
pid=$!

# Wait for a while
sleep 5

# Stop the process using kill
kill "$pid"

# Display a message
echo "Terminated"
