#!/usr/bin/env bash
# This script performs FizzBuzz for numbers from 1 to 100

for current_number in {1..100}
do
  if (( current_number % 3 == 0 && current_number % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( current_number % 3 == 0 ))
  then
    echo "Fizz"
  elif (( current_number % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$current_number"
  fi
done
