#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, saying "Hi" on the 9th iterations
c=1

while [ $c -le 10 ]
do
    echo "Best School"
    if [ $c -eq 9 ]
    then
        echo "Hi"
    fi
    ((c++))
done

